dist: trusty
sudo: required
language: node_js
node_js:
- '14'

branches:
  only:
  - master

before_script:
- npm install -g @angular/cli

script:
- ng lint
- ng build --prod --base-href https://nicholasterry.com
