dist: trusty
sudo: required
language: node_js
node_js:
- '14'

branches:
  only:
  - master

before_script:
- npm install -g @angular/cli
- npm install

script:
- ng lint
- ng build --prod --base-href https://nicholasterry.com

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/nicholasterry-com
  fqdn: nicholasterry.com
  on:
    branch: master
